### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/npm-psc-package-bin-simple#1]
If there is an easy way to support Windows using the same methods, we should. Otherwise, Windows users should use chocolatey to install psc-package.

**Comment by justinwoo** [comment]
Fixed by #5, amazing!

**Comment by srufle** [comment]
Issue with npm global install inside of a docker image.

Create start-testing-image.sh
``` bash
#!/bin/bash
docker run \
    --rm -it \
    node:11-slim \
    bash
```

`chmod +x start-testing-image.sh`
`./start-testing-image.sh`

When inside image
```
mkdir -p test-dir 
cd /test-dir 
apt-get update && apt-get install git vim -y
git clone https://github.com/justinwoo/npm-psc-package-bin-simple.git
cd npm-psc-package-bin-simple/
npm i -g
```

I got the following error. 
```
npm ERR! path /usr/local/lib/node_modules/psc-package-bin-simple/psc-package/psc-package.exe
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/psc-package-bin-simple/psc-package/psc-package.exe'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-27T03_12_41_811Z-debug.log
```

I am unfamiliar with node and javascript, but it seems the issue is happening when untaring.
I did it on the command line and it seems to work fine.
```
wget https://github.com/purescript/psc-package/releases/download/v0.4.2/linux64.tar.gz
tar -xzf linux64.tar.gz -C psc-package/ --strip=1
mv ./psc-package/psc-package ./psc-package/psc-package.exe
```

**Comment by justinwoo** [comment]
Right, you're expected to install this package either by doing `npm i -g psc-package-bin-simple` (which gets it from the npm registry) or by having it as a dependency of your npm-based project by having it in the `"dependencies"` property.

**Comment by taiju** [comment]
@srufle It seems to be a permission problem.
The same problem occurs even below.
```sh
npm i -g purescript
```
Changing the permissions in advance got along well.
```
mkdir -p test-dir 
cd /test-dir 
apt-get update && apt-get install git vim -y
git clone https://github.com/justinwoo/npm-psc-package-bin-simple.git
chmod -R 777 npm-psc-package-bin-simple # -- add this line
cd npm-psc-package-bin-simple/
npm i -g
```

**Comment by dkoontz** [comment]
I can confirm that taiju's fix does solve the issue srufle was encountering. Is there any way to modify the npm installation to do this? I'd be happy to put in a PR.

**Comment by taiju** [comment]
It seems that a common issue in official nodejs docker image.
The following guide will be helpful.

- https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#global-npm-dependencies
- https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user

**Comment by dkoontz** [comment]
I can confirm that following the guide taiju linked to and setting the user to `node` and the 2 environment variables listed does resolves this issue for me using Docker. Thanks!
